AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Digital Identity Fraud Credential Issuer API"

Parameters:
  Environment:
    Description: environment name
    Default: dev
    Type: String
    AllowedValues:
      - dev
      - staging
      - integration
      - prod
    ConstraintDescription: specify dev, staging, integration or prod for environment

Globals:
  Function:
    Timeout: 30 # seconds
    Runtime: java11
    AutoPublishAlias: live
    MemorySize: 256

Resources:

  AccessTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/accesstoken.zip
      Handler: uk.gov.di.ipv.cri.fraud.api.handler.AccessTokenHandler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AccessTokenTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref ParameterCSREnrolURLDev
        - SSMParameterReadPolicy:
            ParameterName: !Ref ParameterBearerAccessTokenTtl
      Events:
        ApiAccessToken:
          Type: Api
          Properties:
            #            Auth:
            #              Authorizer: AWS_IAM
            Path: /token
            Method: post
            RequestParameters:
              - method.request.header.Authorization

  AccessTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub AccessToken-${AWS::StackName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: accessToken
          AttributeType: S
      KeySchema:
        - AttributeName: accessToken
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiryDate
        Enabled: true

  ParameterCSREnrolURLDev:
    Type: AWS::SSM::Parameter
    Properties:
      Name: AccessTokenTableName
      Value: !Sub AccessToken-${AWS::StackName}
      Type: String
      Description: access token table name

  ParameterBearerAccessTokenTtl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: BearerAccessTokenTtl
      Value: 3600
      Type: String
      Description: time to live for the bearer access token (seconds)
