AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Digital Identity Fraud Credential Issuer API"

Parameters:
  CodeSigningConfigArn:
    Type: String
    Default: "none"
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
  Environment:
    Description: "The environment type"
    Type: "String"
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
    ConstraintDescription: must be dev, build, staging, integration or production
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"

Conditions:
  CreateDevResources: !Equals
    - !Ref Environment
    - dev
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
Globals:
  Function:
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    CodeSigningConfigArn: !If
      - CreateDevResources
      - !Ref AWS::NoValue
      - !Ref CodeSigningConfigArn
    Timeout: 30 # seconds
    Runtime: java11
    AutoPublishAlias: live
    MemorySize: 256

Resources:

  AccessTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/accesstoken.zip
      Handler: uk.gov.di.ipv.cri.fraud.api.handler.AccessTokenHandler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AccessTokenTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref ParameterCSREnrolURLDev
        - SSMParameterReadPolicy:
            ParameterName: !Ref ParameterBearerAccessTokenTtl
      Events:
        ApiAccessToken:
          Type: Api
          Properties:
            #            Auth:
            #              Authorizer: AWS_IAM
            Path: /token
            Method: post
            RequestParameters:
              - method.request.header.Authorization

  AccessTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub AccessToken-${AWS::StackName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: accessToken
          AttributeType: S
      KeySchema:
        - AttributeName: accessToken
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiryDate
        Enabled: true

  ParameterCSREnrolURLDev:
    Type: AWS::SSM::Parameter
    Properties:
      Name: AccessTokenTableName
      Value: !Sub AccessToken-${AWS::StackName}
      Type: String
      Description: access token table name

  ParameterBearerAccessTokenTtl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: BearerAccessTokenTtl
      Value: 3600
      Type: String
      Description: time to live for the bearer access token (seconds)
